name: 步步多

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: bubuduo

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【步步多】'
        run: |
          node ./Task/bubuduo.js
        env:
          BBD_ACCESS_KEY: ${{ secrets.BBD_ACCESS_KEY }}
          BBD_DEVICE_ID: ${{ secrets.BBD_DEVICE_ID }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
