name: 百度网盘签到

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: baidu_pan

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【百度网盘签到】'
        run: |
          node ./Task/baidu_pan.js
        env:
          BDYP_COOKIE: ${{ secrets.BDYP_COOKIE }}
