name: 火山极速版提现

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */12 * * *'
  watch:
    types: started
  repository_dispatch:
    types: hotSoon

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【火山极速版提现】'
        run: |
          node ./Task/hotSoon.js
