name: 朗果英语

on:
  workflow_dispatch:
  schedule:
    - cron: '38,48 0,12 * * *'
  watch:
    types: started
  repository_dispatch:
    types: langooo

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【朗果英语】'
        run: |
          node ./Task/langooo.js
        env:
          LANGOO_TOKEN: ${{ secrets.LANGOO_TOKEN }}
          LANGOO_UID: ${{ secrets.LANGOO_UID }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
