name: 墨迹天气

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  watch:
    types: started
  repository_dispatch:
    types: moji

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【墨迹天气】'
        run: |
          node ./Task/moji_weather.js
        env:
          MOJI_TOKEN: ${{ secrets.MOJI_TOKEN }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
