name: 百果园

on:
  workflow_dispatch:
  schedule:
    - cron: '38 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: pagoda

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【百果园】'
        run: |
          node ./Task/pagoda.js
        env:
          PAGODA_TOKEN: ${{ secrets.PAGODA_TOKEN }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
