name: 万年历

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  watch:
    types: started
  repository_dispatch:
    types: wnl

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【万年历】'
        run: |
          node ./Task/perpetual_calendar.js
        env:
          WNL_TOKEN: ${{ secrets.WNL_TOKEN }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
