# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QQ阅读

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  # watch:
  #   types: [started]
  repository_dispatch:
    types: qq_read
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b master https://github.com/ziye66666/JavaScript.git ~/scripts
      - name: '运行 【QQ阅读】'
        run: |
          cd  ~/scripts/Task
          npm install
          node  QQread.js
        env:
          # 专属配置
          QQ_QQreadURL: ${{ secrets.QQ_QQreadURL }}
          # 推送配置
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
