name: 微信端剑三自动签到

on:
  workflow_dispatch:
  schedule:
    - cron: '55 */8 * * *'
  watch:
    types: started
  repository_dispatch:
    types: wechat_xoyo

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【微信端剑三自动签到】'
        run: |
          node ./Task/wechat_xoyoSign.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
